name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Determine if we should tag with latest
        id: determine-if-latest
        uses: actions/github-script@v6
        with:
          script: |
            const version = (context.ref_type == 'branch' ? context.ref_name : context.ref.substring(context.ref.indexOf('v')+1, context.ref.lastIndexOf('.')))
            const latest = (context.payload.repository.default_branch.indexOf(version) == 0)
            console.log("Version: " + version)
            console.log("Latest Branch : " + (latest ? true : false))
            core.setOutput('latest', latest)

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: booellean/node-shell
          flavor: |
            latest=${{ steps.determine-if-latest.outputs.latest }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
